name: Release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Fetch depth 0 is required for Changelog generation
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
