name: Custom_workflow
on: [push]
jobs: 
  checkv: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkw
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm  run build
